export default {
  createdAt: 'u.created_at',
  createdBy: 'u.created_by',
  email: 'u.email',
  externalId: 'u.external_id',
  firstName: 'u.first_name',
  isActive: 'u.is_active',
  lastName: 'u.last_name',
  updateAt: 'u.updated_at',
  updatedBy: 'u.updated_by',
  userId: 'u.user_id',
  username: 'u.username',
  userRoleId: 'u.user_role_id',
  workPhone: 'u.work_phone',
  largeImageId: 'u.large_image_id',
  smallImageId: 'u.small_image_id',
  thumbnailImageId: 'u.thumbnail_image_id',
  phoneProviderUsername: 'u.phone_provider_username',
  positionId: 'u.position_id',
};
